export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS';
export const ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL';

export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAIL = 'GET_EXERCISE_FAIL';

export const ADD_SET = 'ADD_SET';
export const ADD_SET_SUCCESS = 'ADD_SET_SUCCESS';
export const ADD_SET_FAIL = 'ADD_SET_FAIL';

export const EXERCISE_UPDATE = 'EXERCISE_UPDATE';
export const EXERCISE_UPDATE_SUCCESS = 'EXERCISE_UPDATE_SUCCESS';
export const EXERCISE_UPDATE_FAIL = 'EXERCISE_UPDATE_FAIL';

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAIL = 'DELETE_EXERCISE_FAIL';

export const TOGGLE_CREATE_MODAL = 'TOGGLE_CREATE_MODAL';






