export const ADD_EXERCISE = 'ADD_EXERCISE';
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS';
export const ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL';

export const GET_EXERCISE = 'GET_EXERCISE';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAIL = 'GET_EXERCISE_FAIL';

export const ADD_SET = 'ADD_SET';
export const ADD_SET_SUCCESS = 'ADD_SET_SUCCESS';
export const ADD_SET_FAIL = 'ADD_SET_FAIL';

export const METADATA_CHANGE = 'METADATA_CHANGE';
export const METADATA_CHANGE_SUCCESS = 'METADATA_CHANGE_SUCCESS';
export const METADATA_CHANGE_FAIL = 'METADATA_CHANGE_FAIL';

export const DELETE_SET = 'DELETE_SET';
export const DELETE_SET_SUCCESS = 'DELETE_SET_SUCCESS';
export const DELETE_SET_FAIL = 'DELETE_SET_FAIL';



