const quotes = [
  "Just remember, somewhere, a little Chinese girl is warming up with your max",
  "Shut up and train",
  "I don’t care what you USED to bench",
  "The best activities for your health are pumping and humping.",
  "Pain is weakness leaving the body",
  "Don’t have $100.00 shoes and a 10 cent Squat",
  "Big quads without big hamstrings is like steak without potatoes",
  "To be number one, you have to train like you’re number two",
  "That’s a good weight…for a small woman",
  "What good is it to look like Tarzan and play like Jane?",
  "No pain, no gain",
  "Light weight… Yeah buddy!",
  "Curl in the squat rack and die!",
  "No excuses",
  "Bodybuilding is my religion, the gym is my church.",
  "Pain is temporary, quitting is forever.",
  "I don’t do this to be healthy, I do this to get big muscles",
  "There are no shortcuts. The fact that a shortcut is important to you means that you are a pussy.",
  "Anyone under 200 pounds is a woman.",
  "Get ripped, get laid.",
  "Pain is weakness leaving the body.",
  "Being defeated is often a temporary condition. Giving up is what makes it permanent.",
  "Failure is only a temporary change in direction to set you straight for your next success.",
  "If you fail to prepare, you prepare to fail.",
  "The worst thing you can be is average.",
  "Go hard or go home.",
  "EAT BIG, LIFT BIG, GET BIG!",
  "When it starts to hurt, thats when the set starts.",
  "THE HARDEST THING ABOUT EARNING A TITLE IS THE ABILITY TO LIVE UP TO IT",
  "With great size comes great responsibility",
  "Ain’t nothing to it but to do it.",
  "You're not here to talk.",
  "Squat till you puke.",
  "To achieve something you’ve never had before, you must do something you’ve never done before.",
  "Doubt me, hate me, you’re the inspiration I need",
  "You are born weak and die weak, what you are in between those two periods of time is up to you",
  "I don’t care how many reps you do, as long as you lift girl weights you’ll get a girl body!",
  "Strength Within, Pride Throughout",
  "Hard work beats talent when talent doesn’t work hard.",
  "Winners Train, Losers Complain.",
  "A winner never whines.",
  "You don’t demand respect, you earn it.",
  "Good is not enough if better is possible.",
  "If the bar ain’t bending you‘re just pretending",
  "Character is who you are when no one’s watching",
  "The only time Success comes before Work is in the dictionary",
  "I had the goal to be the best from day one."
];

export default quotes;
