export const TOGGLE_KEYBOARD = "TOGGLE_KEYBOARD";
export const KEYBOARD_UPDATE = "KEYBOARD_UPDATE";
export const KEYBOARD_REMOVE_LAST_CHAR = "KEYBOARD_REMOVE_LAST_CHAR";
export const KEYBOARD_NEXT_ELEMENT = 'KEYBOARD_NEXT_ELEMENT';